# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fiji' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fiji
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  target 'FijiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Fiji-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fiji-tvOS

  target 'Fiji-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
